### PR TITLE
pr - export to csv features

### PR DESCRIPTION
**Pull request by saca30**
- added api calls for .csv exports regarding queues, jobs and workers
- added export.html view
- added unit tests

### CODE REVIEW

**Comment by Hannes221** [comment]
Thanks for your contribution @saca30. The data export isn't working properly for me, it just extracts the first job.

**Comment by saca30** [comment]
Hello,
Thank you for bringing this into my attention. Could you provide more details regarding the issue you are having?
The issue is not replicating for me and I could use some extra info in order to do proper debugging.
This is how the export looks for me:
image
I have 2 queues, long_running_tasks and default. In the first queue, there are 2 queued jobs. In the second queue, the start of the id of a failed job can be seen so definitely for me it shows more than the first job.

**Comment by Hannes221** [comment]
You are right! The thing that confused me is that right now, you are saving the JSON structure as a CSV right away. It makes sense to format it properly for CSV or export it in JSON (Maybe even both?).

**Comment by saca30** [comment]
hello @Hannes221,
I added the formatting for .csv as per discussion on PR yesterday.
I foresee adding the .json format in a feature update.
Thank you

**Review by Hannes221 — APPROVED** [review]
Thank you for your contribution! @saca30

**Pull request merged**
